### ISSUE TITLE
"docli ssh-key -l" not working correctly

### ISSUE THREAD

**Issue by techdragon** [yspanchal/docli#1]
```
docli ssh-key -l
Usage: docli ssh-key [OPTIONS]

Error: Missing option, --update requires --name or                      --key option
```

I havent quite worked out how the validation is broken. But this does look to be a case where returning true if there are no extra arguments and were are just trying to list ssh keys, might be appropriate.

**Comment by yspanchal** [comment]
@techdragon it is fixed.
