### ISSUE TITLE
possibly incorrect use of 'nargs' in droplet create command

### ISSUE THREAD

**Issue by techdragon** [yspanchal/docli#3]
Did you really intend to require 10 ssh keys? 

The use of `nargs=10` for the `--sshkeys` flag means that when trying to create a new droplet and specify the ssh key, you need to use a command like this one
`docli droplet -n test-build -s 512m -r sgp1 -i ubuntu-15.10-x64 -b False -I False -P False --sshkeys -- my-ssh-key-name1, , , , , , , , , ,  ,`

Which is significantly different to the method you documented (and I assume intended to be the way it works)

**Comment by yspanchal** [comment]
@techdragon it is fixed.
